# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_desk}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ahmed ElDawy"]
  s.date = %q{2010-01-06}
  s.description = %q{A gem that works as an interface for oDesk APIs that can be used for both desktop and web applications}
  s.email = %q{ahmed.eldawy@badrit.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ruby_desk.rb",
     "lib/ruby_desk/connector.rb",
     "lib/ruby_desk/team_room.rb",
     "ruby_desk.gemspec",
     "test/helper.rb",
     "test/test.rb",
     "test/test_ruby_desk.rb"
  ]
  s.homepage = %q{http://github.com/aseldawy/ruby_desk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Wrapper for oDesk APIs in Ruby}
  s.test_files = [
    "test/test_ruby_desk.rb",
     "test/helper.rb",
     "test/test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

